/:
  controller: Default
  action: default

/test/yves:
  controller: Default
  action: default

/home :
  controller: Home
  action: default


/ajout-utilisateur:
  controller: "User"
  action: "add"

/utilisateur:
  controller: "User"
  action: "default"


/se-connecter:
  controller: "User"
  action: "login"


/s-inscrire:
  controller: "User"
  action: "register"


/mot-de-passe-oublie:
  controller: "User"
  action: "forgotPwd"


/profile:
  controller: "Dashboard"
  action: "profile"

/permissions:
  controller: "Dashboard"
  action: "permissions"
